function MiSalmo() {}
MiSalmo = new MiSalmo();
number = 0;
// textArray
MiSalmo[number++] =
  "1 Bienaventurado el varón que no anduvo en consejo de malos, Ni estuvo en camino de pecadores, Ni en silla de escarnecedores se ha sentado; 2 Sino que en la ley de Jehová está su delicia, Y en su ley medita de día y de noche. 3 Será como árbol plantado junto a corrientes de aguas, Que da su fruto en su tiempo, Y su hoja no cae; Y todo lo que hace, prosperará. 4 No así los malos, Que son como el tamo que arrebata el viento. 5 Por tanto, no se levantarán los malos en el juicio, Ni los pecadores en la congregación de los justos. 6 Porque Jehová conoce el camino de los justos; Mas la senda de los malos perecerá. <br><br><b> -- Capitulo 1 --</b>";
MiSalmo[number++] =
  "1 En Jehová he confiado; ¿Cómo decís a mi alma, Que escape al monte cual ave? 2 Porque he aquí, los malos tienden el arco, Disponen sus saetas sobre la cuerda, Para asaetear en oculto a los rectos de corazón. 3 Si fueren destruidos los fundamentos, ¿Qué ha de hacer el justo? 4 Jehová está en su santo templo; Jehová tiene en el cielo su trono; Sus ojos ven, sus párpados examinan a los hijos de los hombres. 5 Jehová prueba al justo; Pero al malo y al que ama la violencia, su alma los aborrece. 6 Sobre los malos hará llover calamidades; Fuego, azufre y viento abrasador será la porción del cáliz de ellos. 7 Porque Jehová es justo, y ama la justicia; El hombre recto mirará su rostro. <br><br><b> -- Capítulo 11 --</b>";
MiSalmo[number++] =
  "1 ¿Hasta cuándo, Jehová? ¿Me olvidarás para siempre? ¿Hasta cuándo esconderás tu rostro de mí? 2 ¿Hasta cuándo pondré consejos en mi alma, Con tristezas en mi corazón cada día? ¿Hasta cuándo será enaltecido mi enemigo sobre mí? 3 Mira, respóndeme, oh Jehová Dios mío; Alumbra mis ojos, para que no duerma de muerte; 4 Para que no diga mi enemigo: Lo vencí. Mis enemigos se alegrarían, si yo resbalara. 5 Mas yo en tu misericordia he confiado; Mi corazón se alegrará en tu salvación. 6 Cantaré a Jehová, Porque me ha hecho bien. <br><br><b> -- Capítulo 13 --</b>";
MiSalmo[number++] =
  "1 Jehová, ¿quién habitará en tu tabernáculo? ¿Quién morará en tu monte santo? 2 El que anda en integridad y hace justicia, Y habla verdad en su corazón. 3 El que no calumnia con su lengua, Ni hace mal a su prójimo, Ni admite reproche alguno contra su vecino. 4 Aquel a cuyos ojos el vil es menospreciado, Pero honra a los que temen a Jehová. El que aun jurando en daño suyo, no por eso cambia; 5 Quien su dinero no dio a usura, Ni contra el inocente admitió cohecho. El que hace estas cosas, no resbalará jamás. <br><br><b> -- Capítulo 15 --</b>";
MiSalmo[number++] =
  "1 Jehová es mi pastor; nada me faltará. 2 En lugares de delicados pastos me hará descansar; Junto a aguas de reposo me pastoreará. 3 Confortará mi alma; Me guiará por sendas de justicia por amor de su nombre. 4 Aunque ande en valle de sombra de muerte, No temeré mal alguno, porque tú estarás conmigo; Tu vara y tu cayado me infundirán aliento. 5 Aderezas mesa delante de mí en presencia de mis angustiadores; Unges mi cabeza con aceite; mi copa está rebosando. 6 Ciertamente el bien y la misericordia me seguirán todos los días de mi vida, Y en la casa de Jehová moraré por largos días. <br><br><b>-- Capítulo 23 --</b>";
MiSalmo[number++] =
  "1 Júzgame, oh Dios, y defiende mi causa; Líbrame de gente impía, y del hombre engañoso e inicuo. 2 Pues que tú eres el Dios de mi fortaleza, ¿por qué me has desechado? ¿Por qué andaré enlutado por la opresión del enemigo? 3 Envía tu luz y tu verdad; éstas me guiarán; Me conducirán a tu santo monte, Y a tus moradas. 4 Entraré al altar de Dios, Al Dios de mi alegría y de mi gozo; Y te alabaré con arpa, oh Dios, Dios mío. 5 ¿Por qué te abates, oh alma mía, Y por qué te turbas dentro de mí? Espera en Dios; porque aún he de alabarle, Salvación mía y Dios mío. <br><br><b> -- Capítulo 43 --</b>";
MiSalmo[number++] =
  "1 Pueblos todos, batid las manos; Aclamad a Dios con voz de júbilo. 2 Porque Jehová el Altísimo es temible; Rey grande sobre toda la tierra. 3 El someterá a los pueblos debajo de nosotros, Y a las naciones debajo de nuestros pies. 4 El nos elegirá nuestras heredades; La hermosura de Jacob, al cual amó. Selah 5 Subió Dios con júbilo, Jehová con sonido de trompeta. 6 Cantad a Dios, cantad; Cantad a nuestro Rey, cantad; 7 Porque Dios es el Rey de toda la tierra; Cantad con inteligencia. 8 Reinó Dios sobre las naciones; Se sentó Dios sobre su santo trono. 9 Los príncipes de los pueblos se reunieron Como pueblo del Dios de Abraham; 10 Porque de Dios son los escudos de la tierra; El es muy exaltado. <br><br><b> --  Capítulo 47 --</b>";
MiSalmo[number++] =
  "1 Dice el necio en su corazón: No hay Dios. Se han corrompido, e hicieron abominable maldad; No hay quien haga bien. 2 Dios desde los cielos miró sobre los hijos de los hombres, Para ver si había algún entendido Que buscara a Dios. 3 Cada uno se había vuelto atrás; todos se habían corrompido; No hay quien haga lo bueno, no hay ni aun uno. 4 ¿No tienen conocimiento todos los que hacen iniquidad, Que devoran a mi pueblo como si comiesen pan, Y a Dios no invocan? 5 Allí se sobresaltaron de pavor donde no había miedo, Porque Dios ha esparcido los huesos del que puso asedio contra ti; Los avergonzaste, porque Dios los desechó. 6 ¡Oh, si saliera de Sion la salvación de Israel! Cuando Dios hiciere volver de la cautividad a su pueblo, Se gozará Jacob, y se alegrará Israel. <br><br><b> --  Capítulo 53 --</b>";
MiSalmo[number++] =
  "1 Oh Dios, sálvame por tu nombre, Y con tu poder defiéndeme. 2 Oh Dios, oye mi oración; Escucha las razones de mi boca. 3 Porque extraños se han levantado contra mí, Y hombres violentos buscan mi vida; No han puesto a Dios delante de sí. Selah 4 He aquí, Dios es el que me ayuda; El Señor está con los que sostienen mi vida. 5 El devolverá el mal a mis enemigos; Córtalos por tu verdad. 6 Voluntariamente sacrificaré a ti; Alabaré tu nombre, oh Jehová, porque es bueno. 7 Porque él me ha librado de toda angustia, Y mis ojos han visto la ruina de mis enemigos. <br><br><b> --  Capítulo 54 --</b>";
MiSalmo[number++] =
  "1 Oye, oh Dios, mi clamor; A mi oración atiende. 2 Desde el cabo de la tierra clamaré a ti, cuando mi corazón desmayare. Llévame a la roca que es más alta que yo, 3 Porque tú has sido mi refugio, Y torre fuerte delante del enemigo. 4 Yo habitaré en tu tabernáculo para siempre; Estaré seguro bajo la cubierta de tus alas. Selah 5 Porque tú, oh Dios, has oído mis votos; Me has dado la heredad de los que temen tu nombre. 6 Días sobre días añadirás al rey; Sus años serán como generación y generación. 7 Estará para siempre delante de Dios; Prepara misericordia y verdad para que lo conserven. 8 Así cantaré tu nombre para siempre, Pagando mis votos cada día. <br><br><b> --  Capítulo 61 --</b>";
MiSalmo[number++] =
  "1 Dios tenga misericordia de nosotros, y nos bendiga; Haga resplandecer su rostro sobre nosotros; Selah 2 Para que sea conocido en la tierra tu camino, En todas las naciones tu salvación. 3 Te alaben los pueblos, oh Dios; Todos los pueblos te alaben. 4 Alégrense y gócense las naciones,Porque juzgarás los pueblos con equidad, Y pastorearás las naciones en la tierra. Selah 5 Te alaben los pueblos, oh Dios; Todos los pueblos te alaben. 6 La tierra dará su fruto; Nos bendecirá Dios, el Dios nuestro. 7 Bendíganos Dios, Y témanlo todos los términos de la tierra. <br><br><b> --  Capítulo 67 --</b>";
MiSalmo[number++] =
  "1 Oh Dios, acude a librarme; Apresúrate, oh Dios, a socorrerme. 2 Sean avergonzados y confundidos Los que buscan mi vida; Sean vueltos atrás y avergonzados Los que mi mal desean. 3 Sean vueltos atrás, en pago de su afrenta hecha, Los que dicen: ¡Ah! ¡Ah! 4 Gócense y alégrense en ti todos los que te buscan, Y digan siempre los que aman tu salvación: Engrandecido sea Dios. 5 Yo estoy afligido y menesteroso; Apresúrate a mí, oh Dios. Ayuda mía y mi libertador eres tú; Oh Jehová, no te detengas. <br><br><b> --  Capítulo 70 --</b>";
MiSalmo[number++] =
  "1 Dios está en la reunión de los dioses; En medio de los dioses juzga. 2 ¿Hasta cuándo juzgaréis injustamente, Y aceptaréis las personas de los impíos? Selah 3 Defended al débil y al huérfano; Haced justicia al afligido y al menesteroso. 4 Librad al afligido y al necesitado; Libradlo de mano de los impíos. 5 No saben, no entienden, Andan en tinieblas; Tiemblan todos los cimientos de la tierra. 6 Yo dije: Vosotros sois dioses, Y todos vosotros hijos del Altísimo; 7 Pero como hombres moriréis, Y como cualquiera de los príncipes caeréis. 8 Levántate, oh Dios, juzga la tierra; Porque tú heredarás todas las naciones. <br><br><b> --  Capítulo 82 --</b>";
MiSalmo[number++] =
  "1 Jehová reina; se vistió de magnificencia; Jehová se vistió, se ciñó de poder. Afirmó también el mundo, y no se moverá. 2 Firme es tu trono desde entonces; Tú eres eternamente. 3 Alzaron los ríos, oh Jehová, Los ríos alzaron su sonido; Alzaron los ríos sus ondas. 4 Jehová en las alturas es más poderoso Que el estruendo de las muchas aguas, Más que las recias ondas del mar. 5 Tus testimonios son muy firmes; La santidad conviene a tu casa, Oh Jehová, por los siglos y para siempre. <br><br><b> --  Capítulo 93 --</b>";
MiSalmo[number++] =
  "1 Jehová reina; temblarán los pueblos. El está sentado sobre los querubines, se conmoverá la tierra. 2 Jehová en Sion es grande, Y exaltado sobre todos los pueblos. 3 Alaben tu nombre grande y temible; El es santo. 4 Y la gloria del rey ama el juicio; Tú confirmas la rectitud; Tú has hecho en Jacob juicio y justicia. 5 Exaltad a Jehová nuestro Dios, Y postraos ante el estrado de sus pies; El es santo. 6 Moisés y Aarón entre sus sacerdotes, Y Samuel entre los que invocaron su nombre; Invocaban a Jehová, y él les respondía. 7 En columna de nube hablaba con ellos; Guardaban sus testimonios, y el estatuto que les había dado. 8 Jehová Dios nuestro, tú les respondías; Les fuiste un Dios perdonador, Y retribuidor de sus obras. 9 Exaltad a Jehová nuestro Dios, Y postraos ante su santo monte, Porque Jehová nuestro Dios es santo. <br><br><b> --  Capítulo 99 --</b>";
MiSalmo[number++] =
  "1 Cantad alegres a Dios, habitantes de toda la tierra. 2 Servid a Jehová con alegría; Venid ante su presencia con regocijo. 3 Reconoced que Jehová es Dios; El nos hizo, y no nosotros a nosotros mismos; Pueblo suyo somos, y ovejas de su prado. 4 Entrad por sus puertas con acción de gracias, Por sus atrios con alabanza; Alabadle, bendecid su nombre. 5 Porque Jehová es bueno; para siempre es su misericordia, Y su verdad por todas las generaciones. <br><br><b> --  Capítulo 100 --</b>";
MiSalmo[number++] =
  "1 Jehová dijo a mi Señor: Siéntate a mi diestra, Hasta que ponga a tus enemigos por estrado de tus pies. 2 Jehová enviará desde Sion la vara de tu poder; Domina en medio de tus enemigos. 3 Tu pueblo se te ofrecerá voluntariamente en el día de tu poder, En la hermosura de la santidad. Desde el seno de la aurora Tienes tú el rocío de tu juventud. 4 Juró Jehová, y no se arrepentirá: Tú eres sacerdote para siempre Según el orden de Melquisedec. 5 El Señor está a tu diestra; Quebrantará a los reyes en el día de su ira. 6 Juzgará entre las naciones, Las llenará de cadáveres; Quebrantará las cabezas en muchas tierras. 7 Del arroyo beberá en el camino, Por lo cual levantará la cabeza. <br><br><b> --  Capítulo 110 --</b>";
MiSalmo[number++] =
  "1 Alabad, siervos de Jehová, Alabad el nombre de Jehová. 2 Sea el nombre de Jehová bendito Desde ahora y para siempre. 3 Desde el nacimiento del sol hasta donde se pone, Sea alabado el nombre de Jehová. 4 Excelso sobre todas las naciones es Jehová, Sobre los cielos su gloria. 5 ¿Quién como Jehová nuestro Dios, Que se sienta en las alturas, 6 Que se humilla a mirar En el cielo y en la tierra? 7 El levanta del polvo al pobre, Y al menesteroso alza del muladar, 8 Para hacerlos sentar con los príncipes, Con los príncipes de su pueblo. 9 El hace habitar en familia a la estéril, Que se goza en ser madre de hijos. Aleluya. <br><br><b> --  Capítulo 113 --</b>";
MiSalmo[number++] =
  "1 Alabad a Jehová, naciones todas; Pueblos todos, alabadle. 2 Porque ha engrandecido sobre nosotros su misericordia, Y la fidelidad de Jehová es para siempre. Aleluya. <br><br><b> --  Capítulo 117 --</b>";
MiSalmo[number++] =
  "1 A Jehová clamé estando en angustia, Y él me respondió. 2 Libra mi alma, oh Jehová, del labio mentiroso, Y de la lengua fraudulenta. 3 ¿Qué te dará, o qué te aprovechará, Oh lengua engañosa? 4 Agudas saetas de valiente, Con brasas de enebro. 5 ¡Ay de mí, que moro en Mesec, Y habito entre las tiendas de Cedar! 6 Mucho tiempo ha morado mi alma Con los que aborrecen la paz. 7 Yo soy pacífico; Mas ellos, así que hablo, me hacen guerra. <br><br><b> --  Capítulo 120 --</b>";
MiSalmo[number++] =
  "1 Alzaré mis ojos a los montes; ¿De dónde vendrá mi socorro? 2 Mi socorro viene de Jehová, Que hizo los cielos y la tierra. 3 No dará tu pie al resbaladero, Ni se dormirá el que te guarda. 4 He aquí, no se adormecerá ni dormirá El que guarda a Israel. 5 Jehová es tu guardador; Jehová es tu sombra a tu mano derecha. 6 El sol no te fatigará de día, Ni la luna de noche. 7 Jehová te guardará de todo mal; El guardará tu alma. 8 Jehová guardará tu salida y tu entrada Desde ahora y para siempre. <br><br><b> --  Capítulo 121 --</b>";
MiSalmo[number++] =
  "1 A ti alcé mis ojos, A ti que habitas en los cielos. 2 He aquí, como los ojos de los siervos miran a la mano de sus señores, Y como los ojos de la sierva a la mano de su señora, Así nuestros ojos miran a Jehová nuestro Dios, Hasta que tenga misericordia de nosotros. 3 Ten misericordia de nosotros, oh Jehová, ten misericordia de nosotros, Porque estamos muy hastiados de menosprecio. 4 Hastiada está nuestra alma Del escarnio de los que están en holgura, Y del menosprecio de los soberbios. <br><br><b> --  Capítulo 123 --</b>";  
MiSalmo[number++] =
  "1 Los que confían en Jehová son como el monte de Sion, Que no se mueve, sino que permanece para siempre. 2 Como Jerusalén tiene montes alrededor de ella, Así Jehová está alrededor de su pueblo Desde ahora y para siempre. 3 Porque no reposará la vara de la impiedad sobre la heredad de los justos; No sea que extiendan los justos sus manos a la iniquidad. 4 Haz bien, oh Jehová, a los buenos, Y a los que son rectos en su corazón. 5 Mas a los que se apartan tras sus perversidades, Jehová los llevará con los que hacen iniquidad; Paz sea sobre Israel. <br><br><b> --  Capítulo 125 --</b>";
MiSalmo[number++] =
  "1 Cuando Jehová hiciere volver la cautividad de Sion, Seremos como los que sueñan. 2 Entonces nuestra boca se llenará de risa, Y nuestra lengua de alabanza; Entonces dirán entre las naciones: Grandes cosas ha hecho Jehová con éstos. 3 Grandes cosas ha hecho Jehová con nosotros; Estaremos alegres. 4 Haz volver nuestra cautividad, oh Jehová, Como los arroyos del Neguev. 5 Los que sembraron con lágrimas, con regocijo segarán. 6 Irá andando y llorando el que lleva la preciosa semilla; Mas volverá a venir con regocijo, trayendo sus gavillas. <br><br><b> --  Capítulo 126 --</b>";  
MiSalmo[number++] =
  "1 Si Jehová no edificare la casa, En vano trabajan los que la edifican; Si Jehová no guardare la ciudad, En vano vela la guardia. 2 Por demás es que os levantéis de madrugada, y vayáis tarde a reposar, Y que comáis pan de dolores; Pues que a su amado dará Dios el sueño. 3 He aquí, herencia de Jehová son los hijos; Cosa de estima el fruto del vientre. 4 Como saetas en mano del valiente, Así son los hijos habidos en la juventud. 5 Bienaventurado el hombre que llenó su aljaba de ellos; No será avergonzado Cuando hablare con los enemigos en la puerta. <br><br><b> --  Capítulo 127 --</b>";
MiSalmo[number++] =
  "1 Bienaventurado todo aquel que teme a Jehová, Que anda en sus caminos. 2 Cuando comieres el trabajo de tus manos, Bienaventurado serás, y te irá bien. 3 Tu mujer será como vid que lleva fruto a los lados de tu casa; Tus hijos como plantas de olivo alrededor de tu mesa. 4 He aquí que así será bendecido el hombre Que teme a Jehová. 5 Bendígate Jehová desde Sion, Y veas el bien de Jerusalén todos los días de tu vida, 6 Y veas a los hijos de tus hijos. Paz sea sobre Israel. <br><br><b> --  Capítulo 128 --</b>";  
MiSalmo[number++] =
  "1 Mucho me han angustiado desde mi juventud, Puede decir ahora Israel; 2 Mucho me han angustiado desde mi juventud; Mas no prevalecieron contra mí. 3 Sobre mis espaldas araron los aradores; Hicieron largos surcos. 4 Jehová es justo; Cortó las coyundas de los impíos. 5 Serán avergonzados y vueltos atrás Todos los que aborrecen a Sion. 6 Serán como la hierba de los tejados, Que se seca antes que crezca; 7 De la cual no llenó el segador su mano, Ni sus brazos el que hace gavillas. 8 Ni dijeron los que pasaban: Bendición de Jehová sea sobre vosotros; Os bendecimos en el nombre de Jehová. <br><br><b> --  Capítulo 129 --</b>";
MiSalmo[number++] =
  "1 De lo profundo, oh Jehová, a ti clamo. 2 Señor, oye mi voz; Estén atentos tus oídos A la voz de mi súplica. 3 JAH, si mirares a los pecados, ¿Quién, oh Señor, podrá mantenerse? 4 Pero en ti hay perdón, Para que seas reverenciado. 5 Esperé yo a Jehová, esperó mi alma; En su palabra he esperado. 6 Mi alma espera a Jehová Más que los centinelas a la mañana, Más que los vigilantes a la mañana. 7 Espere Israel a Jehová, Porque en Jehová hay misericordia, Y abundante redención con él; 8 Y él redimirá a Israel De todos sus pecados. <br><br><b> --  Capítulo 130 --</b>";  
MiSalmo[number++] =
  "1 ehová, no se ha envanecido mi corazón, ni mis ojos se enaltecieron; Ni anduve en grandezas, Ni en cosas demasiado sublimes para mí. 2 En verdad que me he comportado y he acallado mi alma Como un niño destetado de su madre; Como un niño destetado está mi alma. 3 Espera, oh Israel, en Jehová, Desde ahora y para siempre. <br><br><b> --  Capítulo 131 --</b>";
MiSalmo[number++] =
  "1 ¡Mirad cuán bueno y cuán delicioso es Habitar los hermanos juntos en armonía! 2 Es como el buen óleo sobre la cabeza, El cual desciende sobre la barba, La barba de Aarón, Y baja hasta el borde de sus vestiduras; 3 Como el rocío de Hermón, Que desciende sobre los montes de Sion; Porque allí envía Jehová bendición, Y vida eterna. <br><br><b> --  Capítulo 133 --</b>";  
MiSalmo[number++] =
  "1 Mirad, bendecid a Jehová, Vosotros todos los siervos de Jehová, Los que en la casa de Jehová estáis por las noches. 2 Alzad vuestras manos al santuario, Y bendecid a Jehová. 3 Desde Sion te bendiga Jehová, El cual ha hecho los cielos y la tierra. <br><br><b> --  Capítulo 134 --</b>";
MiSalmo[number++] =
  "1 Te alabaré con todo mi corazón; Delante de los dioses te cantaré salmos. 2 Me postraré hacia tu santo templo, Y alabaré tu nombre por tu misericordia y tu fidelidad; Porque has engrandecido tu nombre, y tu palabra sobre todas las cosas. 3 El día que clamé, me respondiste; Me fortaleciste con vigor en mi alma. 4 Te alabarán, oh Jehová, todos los reyes de la tierra, Porque han oído los dichos de tu boca. 5 Y cantarán de los caminos de Jehová, Porque la gloria de Jehová es grande. 6 Porque Jehová es excelso, y atiende al humilde, Mas al altivo mira de lejos. 7 Si anduviere yo en medio de la angustia, tú me vivificarás; Contra la ira de mis enemigos extenderás tu mano, Y me salvará tu diestra. 8 Jehová cumplirá su propósito en mí; Tu misericordia, oh Jehová, es para siempre; No desampares la obra de tus manos. <br><br><b> --  Capítulo 138 --</b>";  
MiSalmo[number++] =
  "1 Con mi voz clamaré a Jehová; Con mi voz pediré a Jehová misericordia. 2 Delante de él expondré mi queja; Delante de él manifestaré mi angustia. 3 Cuando mi espíritu se angustiaba dentro de mí, tú conociste mi senda. En el camino en que andaba, me escondieron lazo. 4 Mira a mi diestra y observa, pues no hay quien me quiera conocer; No tengo refugio, ni hay quien cuide de mi vida. 5 Clamé a ti, oh Jehová; Dije: Tú eres mi esperanza, Y mi porción en la tierra de los vivientes. 6 Escucha mi clamor, porque estoy muy afligido. Líbrame de los que me persiguen, porque son más fuertes que yo. 7 Saca mi alma de la cárcel, para que alabe tu nombre; Me rodearán los justos, Porque tú me serás propicio. <br><br><b> --  Capítulo 142 --</b>";  
MiSalmo[number++] =
  "1 Cantad a Jehová cántico nuevo; Su alabanza sea en la congregación de los santos.2 Alégrese Israel en su Hacedor; Los hijos de Sion se gocen en su Rey. 3 Alaben su nombre con danza; Con pandero y arpa a él canten. 4 Porque Jehová tiene contentamiento en su pueblo; Hermoseará a los humildes con la salvación. 5 Regocíjense los santos por su gloria, Y canten aun sobre sus camas. 6 Exalten a Dios con sus gargantas, Y espadas de dos filos en sus manos, 7 Para ejecutar venganza entre las naciones, Y castigo entre los pueblos; 8 Para aprisionar a sus reyes con grillos, Y a sus nobles con cadenas de hierro; 9 Para ejecutar en ellos el juicio decretado; Gloria será esto para todos sus santos. Aleluya. <br><br><b> --  Capítulo 149 --</b>";
MiSalmo[number++] =
  "1 Alabad a Dios en su santuario; Alabadle en la magnificencia de su firmamento. 2 Alabadle por sus proezas; Alabadle conforme a la muchedumbre de su grandeza. 3 Alabadle a son de bocina; Alabadle con salterio y arpa. 4 Alabadle con pandero y danza; Alabadle con cuerdas y flautas. 5 Alabadle con címbalos resonantes; Alabadle con címbalos de júbilo. 6 Todo lo que respira alabe a JAH. Aleluya. <br><br><b> --  Capítulo 150 --</b>";  
increment = Math.floor(Math.random() * number);
document.write(MiSalmo[increment]);